### PR TITLE
Replace the best girl from Rem to Nico

### PR DESCRIPTION
**Pull request by faith0811**
Tested, ready to merge.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Hi 死宅真恶心poi, thanks for your contribution. This is a long awaited pull request.

**Comment by HerringtonDarkholme** [comment]
WOW!

I found oxymoron this pull request uses is amusement, yet would you please bake more extensibility in this pattern for, say, listing names like setsuna and touma?

**Comment by faith0811** [comment]
I think we shouldn't disallow the possibility for a person who like Setsuna and Touma both.(They are all great girls, aren't they?) We should be more open about it.
And this might be the subject far away from my original thoughts.

Please reconsider this, and merge the piece into your project.

Nico Nico Ni💕

**Comment by faith0811** [comment]
Not anymore.
Closed.

**Pull request closed without merging**
